export const producerNavItems = [
  { href: "/dashboard/producer", label: "Özet" },
  { href: "/dashboard/producer/scripts", label: "Senaryolar" },
  { href: "/dashboard/producer/purchases", label: "Satın Almalar" },
  { href: "/dashboard/producer/applications", label: "Başvurular" },
  { href: "/dashboard/producer/listings", label: "İlanlar" },
  { href: "/dashboard/producer/requests", label: "Talepler" },
  { href: "/dashboard/producer/messages", label: "Mesajlar" },
  { href: "/dashboard/producer/notifications", label: "Bildirimler" },
  { href: "/dashboard/producer/browse", label: "Keşfet" },
  { href: "/dashboard/producer/billing", label: "Faturalandırma" },
];

export const writerNavItems = [
  { href: "/dashboard/writer", label: "Özet" },
  { href: "/dashboard/writer/profile", label: "Profil" },
  { href: "/dashboard/writer/scripts", label: "Senaryolar" },
  { href: "/dashboard/writer/evaluations", label: "Değerlendirmeler" },
  { href: "/dashboard/writer/toplists", label: "Top Listeler" },
  { href: "/dashboard/writer/featured", label: "Featured" },
  { href: "/dashboard/writer/stats", label: "İstatistikler" },
  { href: "/dashboard/writer/programs", label: "Programlar" },
  { href: "/dashboard/writer/applications", label: "Başvurular" },
  { href: "/dashboard/writer/listings", label: "İlanlar" },
  { href: "/dashboard/writer/requests", label: "Talepler" },
  { href: "/dashboard/writer/messages", label: "Mesajlar" },
  { href: "/dashboard/writer/notifications", label: "Bildirimler" },
  { href: "/dashboard/writer/success", label: "Başarılar" },
  { href: "/dashboard/writer/billing", label: "Faturalandırma" },
];
